kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: k8
    trainer: guru
  annotations: 
    kubernetes.io/created-by: 'guru'
    jenkins.builds.url: 'https://jenkins.guru97s.cloud/transactions/k8-resources'
spec:
  containers:
  - name: nginx
    images: nginx

# Annotations are key-value pairs that are used to attach non-identifying metadata to Kubernetes objects. 
# Various tools that are built over Kubernetes use this metadata attached by annotations to perform actions or enhance resource management. 
# Labels and Annotations are used to attach metadata to Kubernetes objects. This makes annotations important for working with Kubernetes clusters. 
# To learn more about Kubernetes cluster and its architecture refer to Kubernetes – Architecture.