#When you specify a Pod, you can optionally specify how much of each resource a container needs. 
#The most common resources to specify are CPU and memory (RAM); there are others.
kind: Pod
apiVersion: v1
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      #soft limit
      requests:
        cpu: "100m"
        memory: "120Mi"
      #limit should be equal or more than request i.,e hard limit
      limits:
        cpu: "100m"
        memory: "120Mi"