# pod-config will refers guru97s config-map data values which will be accessed 
apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: guru97s
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: guru97s
          key: trainer
