# secrets are used in kubernetes to store confidential information of users,tokens,secret codes,etc
kind: Secret
apiVersion: v1
metadata:
  name: pod-secret
data:
  username: "/YWRtaW4K"
  password: "YWRtaW4AMjMK"