# Here Pod will access the pod-secret data 
kind: Pod
apiVersion: v1
metadata: 
  name: pod-secrets
spec:
  containers: 
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret