# This service is used to call nginx Pod
#  a Service is a method for exposing a network application that is running as one or more Pods in your cluster.
# a Service will be accessed only inside kubernetes cluster only.
apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec: 
  selector: #mention respective pod labels at which service can run
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    