kind: Service
apiVersion: v1
metadata: 
  name: node-port
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 32760