kind: Service
apiVersion: v1
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 32760 #this port will be fixed to the server IP.
  
# $ kubectl get svc
# see nginx-np service is running
# and watch clusterIp of nginx-np service where it is running
# go to ec2 and edit security group of eks-cluster-expense-dev inbound rule by adding custom port, port range of 32760, with CIDR as 0.0.0.0/0
# copy the clusterIP, see the IP of all the nodes of the eks cluster
# you will find one matching, copy the ip, and paste in browser as ip of the node:32760

  # NodePort extends the ClusterIP service and its visibility is internal and external to the cluster. 
  # You can set a NodePort using the NodePort property, this is the port that the service will listen on from outside the cluster. 
  # There is one requirement of using NodePort which is nodes must have public IP addresses. 
  # The port must be in the range between 30000 and 32767 and if you don’t specify the NodePort value Kubernetes will assign it randomly.