kind: Service
apiVersion: v1
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 32760 #this port will be fixed to the server IP.

  # NodePort extends the ClusterIP service and its visibility is internal and external to the cluster. 
  # You can set a NodePort using the NodePort property, this is the port that the service will listen on from outside the cluster. 
  # There is one requirement of using NodePort which is nodes must have public IP addresses. 
  # The port must be in the range between 30000 and 32767 and if you don’t specify the NodePort value Kubernetes will assign it randomly.