#A Deployment provides declarative updates for Pods and ReplicaSets.
#You can define Deployments to create new ReplicaSets, or to remove existing Deployments
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  #thus labels are deployment related labels
  labels:
    app: nginx
    purpose: deployment
    tier: web
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  #pod defintion
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec:
    - name: nginx
      image: nginx
---
# This service is used to call nginx Pod
apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec: 
  selectors:
    app: nginx
    project: test-project
    tier: web
    extra-key: extra-value
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    