#first we need to set filebeat configuration, for that we use configMap
#Accessing nginx logs through filebeat configMap  
#Sending the logs to elasticsearch
#It is related to pod-logs
apiVersion: v1
kind: configMap
metadata: 
  name: filebeat
data: #Setting  filebeat configuration
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]
------
#Adding filebeat sidecar pod to nginx pod  where it can access the logs of the nginx
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: #mounting volumes to nginx container
    - name: nginx-logs
      mountPath: /var/log/nginx/
  - name: filebeat
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumeMounts: #mounting volumes to filebeat container
    - name: filebeat-config
      mountPath: /usr/share/filebeat/filebeat.yml
      subPath: filebeat.yml
    - name: nginx-logs #filebeat accessing nginx logs
      mountPath: /var/log/nginx/
  volumes: #creating volumes 
  - name: nginx-logs
    emptyDir: {}
  - name: filebeat-config
    configMap: #adding configMap filebeat to the volume
      name: filebeat #your filebeat configMap name
      items:
        - key: filebeat.yml
          path: filebeat.yml

