#Tolerations are applied to pods. 
#Tolerations allow the scheduler to schedule pods with matching taints. 
#Tolerations allow scheduling but don't guarantee scheduling
#scheduling pod to run on particular node
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #keep this Always, it will pull the image if present or not
  tolerations:
  - key: "project" #your key while taint an pod
    operator: "Equal" 
    value: "expense"
    effect: "NoSchedule" #your effect which you mentioned while taint the pod
  - key: "project" #your key while taint an pod
    operator: "Exists"
    effect: "NoSchedule"