# Befor running the nodeAffinity make sure that you labeled the nodes of the EKS cluster and applied taints to the nodes of EKS cluster. run the below command to label the node.
# $ kubectl get nodes
# $ kubectl label nodes <node-ip> key=value
# $ kubectl label nodes ip-192-168-42-153.ec2.internal project=expense


#Node affinity is conceptually similar to nodeSelector, allowing you to constrain which nodes your Pod can be scheduled on based on node labels.
#Scheduling pod based on the labels of the node
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project #your key name while labeling a particular node
            operator: In
            values:
            - expense #your value name while labeling a particular node
  containers:
  - name: with-node-affinity
    image: nginx
  tolerations: #applying tolerations because we tainted the node with these labels
  - key: "project" #your key while taint an pod
    operator: "Equal" 
    value: "expense"
    effect: "NoSchedule" #your effect which you mentioned while taint the pod
  - key: "project" #your key while taint an pod
    operator: "Exists"
    effect: "NoSchedule"

# $ kubectl get pods -o wide

# requriedDuringSchedulingIgnoredDuringExecution --> pod will not run even you set affinity. we need to apply tolerations. So in this case until you apply tolerations pod will in pending state.
