#Scheduling pod based on the labels of the node
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project #your key name while labeling a particular node
            operator: In
            values:
            - expense #your value name while labeling a particular node
  containers:
  - name: with-node-affinity
    image: nginx