#Node affinity is conceptually similar to nodeSelector, allowing you to constrain which nodes your Pod can be scheduled on based on node labels.
#Scheduling pod based on the labels of the node
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project #your key name while labeling a particular node
            operator: In
            values:
            - expense #your value name while labeling a particular node
  containers:
  - name: with-node-affinity
    image: nginx
  tolerations: #applying tolerations because we tainted the node with these labels
  - key: "project" #your key while taint an pod
    operator: "Equal" 
    value: "expense"
    effect: "NoSchedule" #your effect which you mentioned while taint the pod
  - key: "project" #your key while taint an pod
    operator: "Exists"
    effect: "NoSchedule"