#scheduling pod to run on different node by using preferredDuringScheduling of nodAffinity
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-1
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: project #your node labels key name
            operator: In
            values:
            - expense #your node labels value name
  containers:
  - name: with-node-affinity-1
    image: nginx