apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:   
    name: pod-1
    purpose: pod-affinity
spec: 
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
------
#Running pod-2 where pod-1 is running using podAffinity
apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
  labels:
    name: pod-2
    purpose: pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: name #your selected pod-1 labels key name
            operator: In
            values:
            - pod-1 #your selected pod-1 labels value name
        topologyKey: topology.kubernetes.io/zone
  containers: 
  - name: nginx
    image: nginx
    imagePullPolicy: Always