# Persistent Volume is used to represent EBS volume inside Kubernetes(EKS), which acts as the bridge between EKS and EBS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi # your volume storage size which is included while creating volume in ec2 resource of AWS
  csi:
    driver: ebs.csi.aws.com #EBS related Drivers
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f41 #your volume ID which is created recently in aws ec2 resource
# $ kubectl get pv
---
# claiming process of PersistentVolume
# PVC---> Persistent Volume Claim, pod should claim,i..e i want the volume from pod
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set, otherwise default StorageClass will be set
  volumeName: ebs-static #your ebs-static volume name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi #should be less than storage of Persistent volume 

# $ kubectl get pvc
# $ kubectl describe pvc ebs-static --> if success then you should get status:Bound
---
#Attaching pvc to pod for the usage of pvc
#PVC should be represented in pod definition
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  labels:
    purpose: ebs-static
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html #nginx html mountpath
  nodeSelector: #scheduilinng node to run based on the availability zone of volume is running
    topology.kubernetes.io/zone: us-east-1c
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static #include your persistant volume name which is created above

# $ kubectl get pods 
# $ kubectl describe pod nginx-static
---
# testing the application based on the internet we should use LoadBalancer Service
kind: Service
apiVersion: v1
metadata: 
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: #selector should have same labels which are included in pod definition of PVC 
    purpose: ebs-static
    project: expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

# $ kubectl get services